### ISSUE TITLE
3DS Keeps Crashing

### ISSUE THREAD

**Issue by ichbaum8** [Mishimam/jesus-giveaway#1]
Pls fix i will give head (no homo)!!!!

**Comment by Mishimam** [comment]
nuh uh

**Comment by ichbaum8** [comment]
you fucking niger kill your self!!!

**Comment by Mishimam** [comment]
![preview](https://github.com/Mishimam/jesus-giveaway/assets/111745275/aa21f0a6-ac92-4105-bc59-0790bddbb4db)

**Comment by Mishimam** [comment]
![rizz](https://github.com/Mishimam/jesus-giveaway/assets/111745275/e1627fac-6442-4fd1-92f5-58e0fe47f914)

**Comment by ichbaum8** [comment]
| Header |
|--------|
| Cell |

**Comment by ichbaum8** [comment]
> kill your self™!!!!!!!!!!!!!!!!!!

**Comment by Mishimam** [comment]
https://github.com/Mishimam/jesus-giveaway/assets/111745275/c98b03fe-1553-4a85-a5c2-74c5cd41b0a3

**Comment by ichbaum8** [comment]
https://github.com/Mishimam/jesus-giveaway/assets/116547421/7c080e1c-f928-428e-af47-0c0e8372558b
