### ISSUE TITLE
schon echt gay

### ISSUE THREAD

**Issue by ichbaum8** [Mishimam/jesus-giveaway#2]
https://github.com/Mishimam/jesus-giveaway/assets/111745275/c98b03fe-1553-4a85-a5c2-74c5cd41b0a3

_Originally posted by @Mishimam in https://github.com/Mishimam/jesus-giveaway/issues/1#issuecomment-1612013834_

**Comment by Mishimam** [comment]
https://github.com/Mishimam/jesus-giveaway/assets/111745275/88252cd0-ac2e-48ad-84f7-56caeed4e4fe

**Comment by ichbaum8** [comment]
https://github.com/Mishimam/jesus-giveaway/assets/116547421/0598a1a5-146b-433a-837a-a0cd4f50851d

**Comment by ichbaum8** [comment]
[https://goku.child-slavery-forum.de/](url)

**Comment by Mishimam** [comment]
![regret](https://github.com/Mishimam/jesus-giveaway/assets/111745275/501c54c1-5cfe-4c34-8c7f-6acdf1a522cd)
