### ISSUE TITLE
You got yo rapist homo thug black balls over there

### ISSUE THREAD

**Issue by ichbaum8** [Mishimam/jesus-giveaway#4]
https://github.com/Mishimam/jesus-giveaway/assets/116547421/c083df4f-9f0d-4664-a022-248870fcf10c

ich zu dir!11

**Comment by Mishimam** [comment]
https://github.com/Mishimam/jesus-giveaway/assets/111745275/ba540fab-134d-4709-b723-3ce9d3ae2079
